CREATE TABLE VENDA
(
	ID_VENDA 		SERIAL 					PRIMARY KEY,
	ID_CLIENTE  	INT						NULL,
	DATA_VENDA		TIMESTAMP				NULL,
	VALOR_TOTAL		DECIMAL(10,2)			NULL,
	CONSTRAINT FK_VENDA FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)