CREATE TABLE CLIENTE
(
	ID_CLIENTE		SERIAL 	PRIMARY KEY,
	NOME			VARCHAR(100)					NULL,
	RUA				VARCHAR(200)					NULL,
	NUMERO			INT								NULL,
	COMPLEMENTO		VARCHAR(100)					NULL,
	BAIRRO			VARCHAR(100)					NULL,
	CEP				VARCHAR(20)						NULL,
	TELEFONE		VARCHAR(20)						NULL,
	EMAIL			VARCHAR(100)					NULL
)