CREATE TABLE ItemVenda
(
	ID_ITEM_VENDA 	SERIAL 	PRIMARY KEY,
	ID_VENDA		INT					NULL,
	ID_PRODUTO		INT					NULL,
	QUANTIDADE		INT					NULL,

	CONSTRAINT FK_VENDA FOREIGN KEY(ID_VENDA) REFERENCES VENDA(ID_VENDA),
	CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
)